version: "3.9"
services:
  server:
    container_name: iot-powersquat-optimize-server
    build: 
      context: .
      dockerfile: Dockerfile

    image: iot-powersquat-optimize
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app/.
    env_file: 
      - .env
    command: python app.py
    network_mode: bridge

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --protocol http2 run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
        - server
    network_mode: host